name: Auth Workflow
on:
  push:
    branches:
      - Main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: 
          name: prod
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: ll
            - name: Run tests
              run: echo "mddedr lol ${{ secrets.KEY }}"