name: Db try

on:
  push:


jobs:
    build:
        environment: 
            name: Production
            url: https://example.com
        runs-on: ubuntu-latest
        steps:
            - name : import repository
              uses: actions/checkout@v2
            - name : check file 
              run: ls -a
            - name : log
              run: echo "Auth workflow ${{ secrets.API }}"
            
