name: Db try
on:
  push:
    branches:
      - Main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: 
          name: devs
        steps:
            - name : Reasuble Workflow
              uses: ./reasuble-workflow/see_repo.yaml
            
